DROP TABLE ADMIN CASCADE CONSTRAINTS;

CREATE TABLE ADMIN (
   ADMIN_ID  VARCHAR2(30),
   ADMIN_PWD VARCHAR2(30) NOT NULL
);

ALTER TABLE ADMIN
ADD CONSTRAINT PK_AID PRIMARY KEY (ADMIN_ID);

COMMENT ON COLUMN ADMIN.ADMIN_ID IS '관리자 아이디';
COMMENT ON COLUMN ADMIN.ADMIN_PWD IS '관리자 비밀번호';




DROP TABLE MEMBER CASCADE CONSTRAINTS;

-- 멤버
CREATE TABLE MEMBER (
   USER_ID   VARCHAR2(30),
   USER_PWD   VARCHAR2(30)   NOT NULL,
   USER_NAME   VARCHAR2(30)   NOT NULL,
   USER_NO   VARCHAR2(30)   NOT NULL,
   PHONE   VARCHAR2(30),
   GENDER   CHAR(1) NOT NULL,
   ADDRESS   VARCHAR2(50) NOT NULL,
   EMAIL   VARCHAR2(30),
   MLIST_NO   NUMBER
);

COMMENT ON COLUMN MEMBER.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '사용자 비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '사용자 이름';
COMMENT ON COLUMN MEMBER.USER_NO IS '주민등록번호';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.GENDER IS '성별';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.MLIST_NO IS '재료리스트 번호';

ALTER TABLE MEMBER
ADD CONSTRAINT PK_UID PRIMARY KEY (USER_ID);
ALTER TABLE MEMBER
ADD CONSTRAINT CK_G CHECK(GENDER IN('M', 'F'));



DROP TABLE QUESTION CASCADE CONSTRAINTS; 
-- 문의하기
CREATE TABLE QUESTION (
   QUS_NO NUMBER,
   QUS_TITLE VARCHAR2(50) NOT NULL,
   QUS_CONTENT VARCHAR2(2000) NOT NULL,
   QUS_BOARD_DATE DATE DEFAULT SYSDATE,
   QUS_PWD VARCHAR2(30),
   USER_ID VARCHAR2(30) NOT NULL
) ;

COMMENT ON COLUMN QUESTION.QUS_NO IS '문의글번호';
COMMENT ON COLUMN QUESTION.QUS_TITLE IS '문의제목';
COMMENT ON COLUMN QUESTION.QUS_CONTENT IS '문의내용';
COMMENT ON COLUMN QUESTION.QUS_BOARD_DATE IS '작성날짜';
COMMENT ON COLUMN QUESTION.QUS_PWD IS '비밀번호';

ALTER TABLE QUESTION
ADD CONSTRAINT PK_QNO PRIMARY KEY (QUS_NO);




DROP TABLE QUSETION_ANSWER CASCADE CONSTRAINTS;
-- 문의하기 답변
CREATE TABLE QUSETION_ANSWER (
	QUS_NO	NUMBER,
	QUS_ANS_CONTENT	VARCHAR2(2000)	NOT NULL,
	QUS_ANS_DATE	DATE	DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN QUSETION_ANSWER.QUS_NO IS '문의글번호';
COMMENT ON COLUMN QUSETION_ANSWER.QUS_ANS_CONTENT IS '답변내용';
COMMENT ON COLUMN QUSETION_ANSWER.QUS_ANS_DATE IS '답변날짜';

ALTER TABLE QUSETION_ANSWER
ADD CONSTRAINT PK_QANO PRIMARY KEY (QUS_NO);
ALTER TABLE QUSETION_ANSWER
ADD CONSTRAINT FK_QNO FOREIGN KEY (QUS_NO) REFERENCES QUESTION;


DROP TABLE DECLARATION CASCADE CONSTRAINTS;
-- 신고하기
CREATE TABLE DECLARATION (
    DE_NO NUMBER,
    DE_TITLE VARCHAR2(50) NOT NULL,
    DE_BOARD_DATE DATE DEFAULT SYSDATE,
    DE_CONTENT VARCHAR2(2000) NOT NULL,
    DE_PWD VARCHAR2(20) NOT NULL,
    USER_ID VARCHAR2(30) NOT NULL    
);

COMMENT ON COLUMN DECLARATION.DE_NO IS '신고글 번호';
COMMENT ON COLUMN DECLARATION.DE_TITLE IS '신고글 제목';
COMMENT ON COLUMN DECLARATION.DE_CONTENT IS '신고 내용';
COMMENT ON COLUMN DECLARATION.DE_BOARD_DATE IS '작성날짜';
COMMENT ON COLUMN DECLARATION.DE_PWD IS '비밀번호';
    
ALTER TABLE DECLARATION
ADD CONSTRAINT PK_DENO PRIMARY KEY (DE_NO);



DROP TABLE DECLARATION_ANSWER CASCADE CONSTRAINTS;
-- 신고하기 답변
CREATE TABLE DECLARATION_ANSWER (
	DE_NO	NUMBER,
	DE_ANS_CONTENT	VARCHAR2(2000) NOT NULL,
	DE_ANS_DATE	DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN DECLARATION_ANSWER.DE_NO IS '신고글 번호';
COMMENT ON COLUMN DECLARATION_ANSWER.DE_ANS_CONTENT IS '답변 내용';
COMMENT ON COLUMN DECLARATION_ANSWER.DE_ANS_DATE IS '답변 날짜';

ALTER TABLE DECLARATION_ANSWER
ADD CONSTRAINT PK_DN PRIMARY KEY (DE_NO);
ALTER TABLE DECLARATION_ANSWER
ADD CONSTRAINT FK_DN FOREIGN KEY (DE_NO) REFERENCES DECLARATION;




-- 한식 레시피
DROP TABLE KOREA_RECIPE CASCADE CONSTRAINTS;

CREATE TABLE KOREA_RECIPE (
   R_BOARD_NO NUMBER,   
   R_BOARD_TITLE VARCHAR2(50)   NOT NULL,
   R_BOARD_CONTENT   VARCHAR2(2000)   NOT NULL,
   R_BOARD_DATE   DATE DEFAULT SYSDATE,
   LM_LIST   NUMBER   NOT NULL,
   R_BOARD_FILE   VARCHAR2(30),
   COOK_NO   NUMBER   NOT NULL,
   RB_BOARD_NO   NUMBER   NOT NULL,
   USER_ID   VARCHAR2(30)   NOT NULL,
   COMMENT_NO   NUMBER   NOT NULL,
   ADMIN_ID VARCHAR2(30)   NOT NULL,
   LH_BOARD_NO NUMBER NOT NULL   
);

ALTER TABLE KOREA_RECIPE
ADD CONSTRAINT PK_BNO PRIMARY KEY (R_BOARD_NO);

COMMENT ON COLUMN KOREA_RECIPE.R_BOARD_NO IS '글 번호';
COMMENT ON COLUMN KOREA_RECIPE.R_BOARD_TITLE IS '제목';
COMMENT ON COLUMN KOREA_RECIPE.R_BOARD_CONTENT IS '내용';
COMMENT ON COLUMN KOREA_RECIPE.R_BOARD_DATE IS '작성 날짜';
COMMENT ON COLUMN KOREA_RECIPE.LM_LIST IS '재료 리스트 번호';
COMMENT ON COLUMN KOREA_RECIPE.R_BOARD_FILE IS '첨부파일';
COMMENT ON COLUMN KOREA_RECIPE.COOK_NO IS '요리방법 번호';
COMMENT ON COLUMN KOREA_RECIPE.RB_BOARD_NO IS '게시판 번호';
COMMENT ON COLUMN KOREA_RECIPE.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN KOREA_RECIPE.COMMENT_NO IS '댓글 번호';
COMMENT ON COLUMN KOREA_RECIPE.ADMIN_ID IS '관리자 아이디';
COMMENT ON COLUMN KOREA_RECIPE.LH_BOARD_NO IS '좋아요 싫어요 글 번호';


DROP TABLE MSQUARE CASCADE CONSTRAINTS;
-- 만남의 광장
CREATE TABLE MSQUARE (
  S_BOARD_NO NUMBER,
  S_BOARD_NAME VARCHAR2(50) NOT NULL,
  S_BOARD_CONTENT VARCHAR2(2000) NOT NULL,
  S_BOARD_DATE DATE DEFAULT SYSDATE, 
  S_BOARD_FILE VARCHAR2(30),
  SB_BOARD_NO NUMBER NOT NULL,
  USER_ID VARCHAR2(30) NOT NULL,
  COMMENT_NO NUMBER NOT NULL,
  ADMIN_ID VARCHAR2(30) NOT NULL
);

ALTER TABLE MSQUARE
ADD CONSTRAINT PK_SBNO PRIMARY KEY (S_BOARD_NO);


COMMENT ON COLUMN MSQUARE.S_BOARD_NO IS '글 번호';
COMMENT ON COLUMN MSQUARE.S_BOARD_NAME IS '제목';
COMMENT ON COLUMN MSQUARE.S_BOARD_CONTENT IS '내용';
COMMENT ON COLUMN MSQUARE.S_BOARD_DATE IS '작성날짜';
COMMENT ON COLUMN MSQUARE.S_BOARD_FILE IS '첨부파일';
COMMENT ON COLUMN MSQUARE.SB_BOARD_NO IS '게시판 번호';





DROP TABLE B_COMMENT CASCADE CONSTRAINTS;

CREATE TABLE B_COMMENT (
	COMMENT_NO NUMBER,
	USER_ID	VARCHAR2(30) NOT NULL,
	COMM_CONTENT VARCHAR2(2000) NOT NULL,
	COMM_DATE DATE DEFAULT SYSDATE,
	B_BOARD_NO NUMBER NOT NULL
);

COMMENT ON COLUMN B_COMMENT.COMMENT_NO IS '댓글번호';
COMMENT ON COLUMN B_COMMENT.USER_ID IS '아이디';
COMMENT ON COLUMN B_COMMENT.COMM_CONTENT IS '댓글 내용';
COMMENT ON COLUMN B_COMMENT.COMM_DATE IS '댓글 날짜';
COMMENT ON COLUMN B_COMMENT.B_BOARD_NO IS '게시판 번호';

ALTER TABLE B_COMMENT
ADD CONSTRAINT PK_CNO PRIMARY KEY (COMMENT_NO);





DROP TABLE MY_RECIPE CASCADE CONSTRAINTS;
-- 나만의 레시피
CREATE TABLE MY_RECIPE (
	M_BOARD_NO NUMBER,
	M_BOARD_NAME VARCHAR2(50) NOT NULL,
	M_BOARD_CONTENT	VARCHAR2(2000),
	M_BOARD_DATE DATE DEFAULT SYSDATE,
	M_BOARD_FILE VARCHAR2(30),
	MB_BOARD_NO	NUMBER NOT NULL,
	USER_ID	VARCHAR2(30) NOT NULL,
	COMMENT_NO NUMBER NOT NULL,
	ADMIN_ID VARCHAR2(30) NOT NULL,
	LH_BOARD_NO	NUMBER NOT NULL,
	LM_LIST NUMBER NOT NULL
);
COMMENT ON COLUMN MY_RECIPE.M_BOARD_NO IS '글 번호';
COMMENT ON COLUMN MY_RECIPE.M_BOARD_NAME IS '제목';
COMMENT ON COLUMN MY_RECIPE.M_BOARD_CONTENT IS '내용';
COMMENT ON COLUMN MY_RECIPE.M_BOARD_DATE IS '작성 날짜';
COMMENT ON COLUMN MY_RECIPE.M_BOARD_FILE IS '첨부파일';
COMMENT ON COLUMN MY_RECIPE.M_BOARD_NO IS '게시판 번호';
COMMENT ON COLUMN MY_RECIPE.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN MY_RECIPE.COMMENT_NO IS '댓글 번호';
COMMENT ON COLUMN MY_RECIPE.ADMIN_ID IS '관리자 아이디';
COMMENT ON COLUMN MY_RECIPE.LH_BOARD_NO IS '좋아요 싫어요 글 번호';
COMMENT ON COLUMN MY_RECIPE.LM_LIST IS '재료 리스트 번호';

ALTER TABLE MY_RECIPE ADD CONSTRAINT PK_MBO PRIMARY KEY (M_BOARD_NO);



DROP TABLE LH CASCADE CONSTRAINTS;
-- 좋아요 싫어요
CREATE TABLE LH (
	LH_BOARD_NO NUMBER,
	LIKE_COUNT NUMBER DEFAULT 0,
	HATE_COUNT NUMBER DEFAULT 0
);
COMMENT ON COLUMN LH.LH_BOARD_NO IS '좋아요 싫어요 글번호';
COMMENT ON COLUMN LH.LIKE_COUNT IS '좋아요 카운트';
COMMENT ON COLUMN LH.HATE_COUNT IS '싫어요 카운트';
ALTER TABLE LH 
ADD CONSTRAINT PK_LBN PRIMARY KEY (LH_BOARD_NO);




DROP TABLE MY_MATERIAL_LIST CASCADE CONSTRAINTS;
-- 회원 재료 리스트
CREATE TABLE MY_MATERIAL_LIST(
 USER_ID VARCHAR2(30),
LM_LIST NUMBER
);
COMMENT ON COLUMN MY_MATERIAL_LIST.USER_ID IS '아이디';
COMMENT ON COLUMN MY_MATERIAL_LIST.LM_LIST IS '레시피 재료 번호';

ALTER TABLE MY_MATERIAL_LIST
ADD CONSTRAINT PK_MMLUID PRIMARY KEY (USER_ID);
ALTER TABLE MY_MATERIAL_LIST
ADD CONSTRAINT FK_MLUID FOREIGN KEY (USER_ID) REFERENCES MEMBER;
ALTER TABLE MY_MATERIAL_LIST
ADD CONSTRAINT FK_MM_LIST FOREIGN KEY (LM_LIST) REFERENCES LECIPE_MATERIAL_LIST;



--레시피 재료 리스트
DROP TABLE LECIPE_MATERIAL_LIST CASCADE CONSTRAINTS;
CREATE TABLE LECIPE_MATERIAL_LIST(
LM_LIST NUMBER,
R_BOARD_NO NUMBER,
MA_NO NUMBER
);
COMMENT ON COLUMN LECIPE_MATERIAL_LIST.LM_LIST IS '레시피 재료 번호';
COMMENT ON COLUMN LECIPE_MATERIAL_LIST.R_BOARD_NO IS '글 번호';
COMMENT ON COLUMN LECIPE_MATERIAL_LIST.MA_NO IS '재료 번호';

ALTER TABLE LECIPE_MATERIAL_LIST
ADD CONSTRAINT PK_LM_LIST PRIMARY KEY (LM_LIST);


--재료
DROP TABLE MATERIAL CASCADE CONSTRAINTS;
CREATE TABLE MATERIAL(
MA_NO NUMBER,
MA_NAME VARCHAR2(30),
TYPE_NAME VARCHAR2(30)
);
COMMENT ON COLUMN MATERIAL.MA_NO IS '재료 번호';
COMMENT ON COLUMN MATERIAL.MA_NAME IS '재료 이름';
COMMENT ON COLUMN MATERIAL.TYPE_NAME  IS '상태 이름';

ALTER TABLE MATERIAL
ADD CONSTRAINT PK_MA_NO PRIMARY KEY (MA_NO);


ALTER TABLE LECIPE_MATERIAL_LIST
ADD CONSTRAINT FK_RBNO FOREIGN KEY(R_BOARD_NO) REFERENCES KOREA_RECIPE;
ALTER TABLE LECIPE_MATERIAL_LIST
ADD CONSTRAINT FK_MANO FOREIGN KEY(MA_NO) REFERENCES MATERIAL;


-- 만남의 광장
ALTER TABLE MSQUARE
ADD CONSTRAINT FK_SBUID FOREIGN KEY (USER_ID) REFERENCES MEMBER;
ALTER TABLE MSQUARE
ADD CONSTRAINT FK_SBCN FOREIGN KEY (COMMENT_NO) REFERENCES B_COMMENT;
ALTER TABLE MSQUARE
ADD CONSTRAINT FK_SBADIN FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN;

-- 한식 레시피
ALTER TABLE KOREA_RECIPE
ADD CONSTRAINT FK_RUID FOREIGN KEY (USER_ID) REFERENCES MEMBER;
ALTER TABLE KOREA_RECIPE
ADD  CONSTRAINT FK_CMNO FOREIGN KEY (COMMENT_NO) REFERENCES B_COMMENT;
ALTER TABLE KOREA_RECIPE
ADD CONSTRAINT FK_AMID FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN;
ALTER TABLE KOREA_RECIPE
ADD CONSTRAINT FK_LHNO FOREIGN KEY (LH_BOARD_NO) REFERENCES LH;
ALTER TABLE KOREA_RECIPE
ADD CONSTRAINT FK_KLM_LIST FOREIGN KEY (LM_LIST) REFERENCES LECIPE_MATERIAL_LIST;


-- 문의하기
ALTER TABLE QUESTION
ADD CONSTRAINT FK_UID FOREIGN KEY (USER_ID) REFERENCES MEMBER;


-- 댓글
ALTER TABLE B_COMMENT
ADD CONSTRAINT FK_CUID FOREIGN KEY (USER_ID) REFERENCES MEMBER;


-- 나만의 레시피
ALTER TABLE  MY_RECIPE ADD CONSTRAINT FK_MRUID  FOREIGN KEY (USER_ID) REFERENCES MEMBER;
ALTER TABLE  MY_RECIPE ADD CONSTRAINT FK_MRCMNO FOREIGN KEY (COMMENT_NO) REFERENCES B_COMMENT;
ALTER TABLE  MY_RECIPE ADD CONSTRAINT FK_MRAMID FOREIGN KEY (ADMIN_ID) REFERENCES ADMIN;
ALTER TABLE  MY_RECIPE ADD CONSTRAINT FK_MRLHNO FOREIGN KEY (LH_BOARD_NO) REFERENCES LH;
ALTER TABLE  MY_RECIPE ADD CONSTRAINT FK_MR_LIST FOREIGN KEY (LM_LIST) REFERENCES LECIPE_MATERIAL_LIST;

-- 신고하기
ALTER TABLE DECLARATION
ADD CONSTRAINT FK_DUID FOREIGN KEY (USER_ID) REFERENCES MEMBER;  -- UID가 사용중이라 DUID로 변경
